// Craig Foulkrod
// 06082026-06302026

package me.apotterhead.cheers.vars;

import java.util.List;
import java.util.ArrayList;

/**
 * {@code SerialObject} is a class that represents an {@code Object} that
 * is being serialized. The {@code Object} in question could be either the
 * primary {@code Object} being serialzied, or an {@code Object} that is
 * referenced by another {@code Object} in the serialization chain.
 *
 * @since 1.0.0
 */
public class SerialObject {
    private final String uuid;
    private final String className;
    private final List<SerialVariable> variables;
    
    /**
     * Constructs a new {@code SerialObject} with a {@code String} representing
     * a unique ID ({@code uuid}), and a {@code String} representing a
     * {@code class}. The formatting of the {@code className} varaible should match
     * exactly what is returned by {@link Class#getName}.
     *
     * @param uuid a {@code String} representing a unique ID for the {@code Object}
     * @param className a {@code String} representing the {@code class} of the
     * {@code Object}. The formatting should be consistent with what is returned by
     * {@link Class#getName}
     */
    public SerialObject( String uuid, String className ) {
        this.uuid = uuid;
        this.className = className;
        variables = new ArrayList<>();
    }
    
    /**
     * Adds a {@code SerialVariable} to the {@code SerialObject} variable list.
     *
     * @param variable the {@code SerialVariable} to be added to the list of variables
     *                 for this {@code SerialObject}
     */
    public void addVariable( SerialVariable variable ) {
        variables.add( variable );
    }
    
    /**
     * Returns a {@code String} representing the unique ID of the {@code Object}.
     *
     * @return a {@code String} representing the unique ID of the {@code Object}
     */
    public String getUUID() {
        return uuid;
    }
    
    /**
     * Returns a {@code String} representing the {@code class} of the {@code Object}.
     * The formatting should match exactly what is returned by {@link Class#getName}.
     *
     * @return a {@code String} representing the {@code class} of the {@code Object}.
     * The formatting should be consistent with what is returned by
     * {@link Class#getName}
     */
    public String getClassName() {
        return className;
    }
    
    /**
     * Returns a {@code SerialVariable} {@code List} containg all the varaiables
     * that have been added to this {@code SerialObject}.
     *
     * @return a {@code SerialVariable} {@code List} containg all the varaiables
     * that have been added to this {@code SerialObject}
     */
    public List<SerialVariable> getVariables() {
        return variables;
    }
    
    /**
     * Returns a serialized version of the respective {@code Object}. Every
     * {@code Object} in the final product returnd by
     * {@link me.apotterhead.cheers.Serializer#serialize } is generated by
     * this method.
     * <p>
     * The method returns a {@code String} in the format of
     * {@code uuid:TYPE:"value" { SerialVariables }}. Most of the time, {@code TYPE}
     * will be {@code OBJECT}.
     *
     * @return a {@code String} representation of the {@code Object}. This is
     * what is written to represent the variable in the serialization process.
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append( uuid ).append( ":OBJECT:" ).append( className ).append( " {\n" );
        
        for( SerialVariable var : variables )
            sb.append( "\t" ).append( var.toString() ).append( "\n" );
        
        sb.append( "}" );
        return sb.toString();
    }
}
