// Craig Foulkrod
// 06082026-06282026

package me.apotterhead.cheers.vars;

/**
 * {@code SerialVariable} is an interface that represents a variable inside a
 * {@link SerialObject}.
 * <p>
 * {@code SerialVariable} helps act as an intermediary between the variables
 * in the orignal {@code Object} and the serialzied {@code String}.
 *
 * @since 1.0.0
 */
public interface SerialVariable {
    /**
     * Returns a {@code String} representation of the variable's name. This must
     * match exactly what the name of the variable was in the original {@code Object}
     * in order to be propperly deserialized.
     *
     * @return a {@code String} representation of the variable's name
     */
        String getName();
    
    /**
     * Returns a serialized version of the variable. Every variable in the final product
     * returnd by {@link me.apotterhead.cheers.Serializer#serialize } is generated by this
     * method.
     * <p>
     * Each implementation should return in the format of {@code "name:TYPE:value"}.
     *
     * @return a {@code String} representation of the variable. This is what is
     * written to represent the variable in the serialization process.
     */
        String toString();
}
